export const gameContainer = document.querySelector(".trivia-container");
export const countDownContainer = document.querySelector(".countdown");
export const spanCountDown = document.querySelector(".countdown span");
export const menuContainer = document.querySelector(".setup-container");
export const selectCategoryInput = document.querySelector("#category");
export const questionEl = document.querySelector(".trivia-game h1");
export const labelChoicesEls = document.querySelectorAll(".trivia-game label");
export const inputChoicesEls = document.querySelectorAll("input[type='radio']");
export const nextBtn = document.querySelector(".next-btn");
export const circles = document.querySelectorAll(".circle");
export const progressBar = document.querySelector(".progress-bar");
